//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciept
    {
        public int REID { get; set; }
        public int RID { get; set; }
        public string TravelReciept { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
