//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInfo
    {
        public int RID { get; set; }
        public int CID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> VacationDays { get; set; }
        public int TID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Report Report { get; set; }
    }
}
