//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Prepayments = new HashSet<Prepayment>();
            this.Reports = new HashSet<Report>();
            this.Bosses = new HashSet<Boss>();
        }
    
        public int UID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public string Username { get; set; }
        public string PW { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public int BID { get; set; }
    
        public virtual Boss Boss { get; set; }
        public virtual ICollection<Prepayment> Prepayments { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Boss> Bosses { get; set; }
    }
}
